# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-web-base@sha256:ecd54b9d6557287f3db5ca4b16d03f5176bac71085526a6888da5c72b0460dbd

USER root

WORKDIR /home/ubuntu/web

COPY Caddyfile .
RUN mv Caddyfile /etc/caddy/Caddyfile

COPY package.json .
COPY package-lock.json .
COPY server.mjs .

RUN mkdir -p public
RUN cp /home/ubuntu/.lotus-local-net/token public/token

RUN chown -R ubuntu. .

USER ubuntu

RUN npm install

EXPOSE 3000

CMD bash -c 'caddy start -config /etc/caddy/Caddyfile; node server.mjs'
