# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-web-base@sha256:286802d37c7b1c0e0cbcbc522d1462305159c262d56eeaa945fc8f99bb1010d8

USER root

WORKDIR /home/ubuntu/web

COPY Caddyfile .
RUN mv Caddyfile /etc/caddy/Caddyfile

COPY package.json .
COPY package-lock.json .
COPY server.mjs .

RUN mkdir -p public
RUN cp /home/ubuntu/.lotus-local-net/token public/token

RUN chown -R ubuntu. .

USER ubuntu

RUN npm install

EXPOSE 3000

CMD bash -c 'caddy start -config /etc/caddy/Caddyfile; node server.mjs'
