# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-ready@sha256:97692a8bc7292defb4368140008acdbd08207adda9bf6c43a61ccfebf09b1299

USER root

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt install -y nodejs

# Caddy server
# https://caddyserver.com/docs/install#debian-ubuntu-raspbian

RUN apt install -y debian-keyring debian-archive-keyring apt-transport-https
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
RUN apt-get update
RUN apt install -y caddy

RUN apt upgrade -y


WORKDIR /home/ubuntu/web

COPY fil-hello-world-actor fil-hello-world-actor

RUN chown -R ubuntu. .

USER ubuntu

WORKDIR /home/ubuntu/web/fil-hello-world-actor

RUN rustup update
RUN rustup toolchain install nightly
RUN rustup target add wasm32-unknown-unknown --toolchain nightly
RUN rustup default nightly
RUN rm -f rust-toolchain
RUN rustup show
RUN cargo clean
RUN cargo build

WORKDIR /home/ubuntu/web

