# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-ready@sha256:354e4a06a4b8b1a150e3141f36c31d6265b529dcd205fcf2939a24c8f7450e3a

USER root

# Solidity
# https://docs.soliditylang.org/en/v0.8.16/installing-solidity.html

RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ethereum/ethereum
RUN apt-get update
RUN apt-get install -y solc

# Node

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt install -y nodejs

# Caddy server
# https://caddyserver.com/docs/install#debian-ubuntu-raspbian

RUN apt install -y debian-keyring debian-archive-keyring apt-transport-https
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
RUN apt-get update
RUN apt install -y caddy

RUN apt upgrade -y


WORKDIR /home/ubuntu/web

COPY fil-hello-world-actor fil-hello-world-actor

RUN chown -R ubuntu. .

USER ubuntu

WORKDIR /home/ubuntu/web/fil-hello-world-actor

# Rust

RUN rustup update
RUN rustup toolchain install nightly
RUN rustup target add wasm32-unknown-unknown --toolchain nightly
RUN rustup default nightly
RUN rm -f rust-toolchain
RUN rustup show
RUN cargo clean
RUN cargo build

WORKDIR /home/ubuntu/web

