# syntax=docker/dockerfile:1.4

FROM ghcr.io/jimpick/lotus-fvm-localnet-web-base@sha256:5709baf5fb6cd112bd4179827753fda0e279ad4128fd1c06a1f854d8cf49bfec

USER root

WORKDIR /home/ubuntu/web

COPY Caddyfile .
RUN mv Caddyfile /etc/caddy/Caddyfile

COPY package.json .
COPY package-lock.json .
COPY server.mjs .

RUN mkdir -p public
RUN cp /home/ubuntu/.lotus-local-net/token public/token

RUN chown -R ubuntu. .

USER ubuntu

RUN npm install

EXPOSE 3000

CMD bash -c 'caddy start -config /etc/caddy/Caddyfile; node server.mjs'
